server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Redirige cualquier ruta desconocida a index.html para que Vue Router la gestione
    location / {
        try_files $uri $uri/ /index.html;
    }
}
